name: oidc-poc
on:
    push:
        branches:
            - '*'
jobs:
    auth:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Get ID Token from GitHub
              run: |
                  ID_TOKEN=$(curl -sLS -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                  "${ACTIONS_ID_TOKEN_REQUEST_URL}" | jq .value | tr -d '"')
                  echo "ID_TOKEN=${ID_TOKEN}" >> $GITHUB_ENV
                  echo "✅ GitHub OIDC Token received."

            - name: Exchange ID Token for JFrog Access Token
              env:
                  ID_TOKEN: ${{ env.ID_TOKEN }}
                  JFROG_PLATFORM_URL: https://artifactory.stage.0658b-techopscore.com
              run: |
                  ACCESS_TOKEN=$(curl -XPOST -H "Content-Type: application/json" \
                    "${JFROG_PLATFORM_URL}/access/api/v1/oidc/token" \
                    -d "{\"grant_type\": \"urn:ietf:params:oauth:grant-type:token-exchange\", \"subject_token_type\":\"urn:ietf:params:oauth:token-type:id_token\", \"subject_token\": \"${ID_TOKEN}\", \"provider_name\": \"github-oidc\"}" | jq .access_token | tr -d '"')
                  echo "ACCESS_TOKEN=${ACCESS_TOKEN}" >> $GITHUB_ENV
                  echo "✅ JFrog Access Token received."

            - name: Validate JFrog Authentication
              env:
                  JFROG_PLATFORM_URL: https://artifactory.stage.0658b-techopscore.com
                  ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
              run: |
                  curl -H "Authorization: Bearer ${ACCESS_TOKEN}" \
                    "${JFROG_PLATFORM_URL}/artifactory/api/system/ping"
                  echo "✅ JFrog Authentication Successful."
